feat: Composed story
nielsen-oss/superset-viz-plugins pull request #19
Opened 2020-12-31 09:48 UTC by simchaNielsen

2020-12-31 18:18 UTC, MatanBobi requested changes

2020-12-31 18:18 UTC, MatanBobi commented on package.json
> +    "lint": "eslint plugins/**/*.{ts,tsx}",
You don't want the lint command to run on the `packages` folder?

2020-12-31 18:18 UTC, MatanBobi commented on plugins/plugin-chart-composed/package.json
> -    "@superset-ui/core": "^0.16.11",
is that not a peer dependency anymore?

2020-12-31 18:18 UTC, MatanBobi commented on plugins/plugin-chart-waterfall/test/__mocks__/waterfallProps.ts
> +    "numbersFormat": "SMART_NUMBER",
I'd probably think of putting this in a constant since you're using it many times..

2020-12-31 18:18 UTC, MatanBobi commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +import {CHART_SUB_TYPES, CHART_TYPES, Layout} from '../../plugins/plugin-chart-composed/src/components/utils';
Maybe it would be nicer to locate the stories inside the package and that way every package will include it's own stories?

2020-12-31 18:18 UTC, MatanBobi commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +import {ChartProps, supersetTheme, ThemeProvider} from "@superset-ui/core";
Did lint run on this file? I think it's missing spaces..

2020-12-31 18:18 UTC, MatanBobi commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +    return <div>
Do you really need the div here or you can use a `Fragment`?

2020-12-31 18:18 UTC, MatanBobi commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +      {`SubType "${args.chartSubType}" is not applied for Bars Chart, please change "chartSubType" property to:`}
This sounds like something that should be an exception and not a message..

2020-12-31 18:18 UTC, MatanBobi commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +    data={transformProps({...barsHorizontalLegendTop, queriesData: args.queriesData} as unknown as ChartProps).data}
I'm not a huge fan of `as unknown as T`, any way to do this differently?

2020-12-31 18:18 UTC, MatanBobi commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +    data={transformProps({...barsHorizontalLegendTop, queriesData: args.queriesData} as unknown as ChartProps).data}
Also, I'd prefer separating between the object creation and calling the function.. IMO it will look much better if there will be a constant and you'll just pass it.

2021-01-03 06:02 UTC, simchaNielsen commented on package.json
> +    "lint": "eslint plugins/**/*.{ts,tsx}",
it has some issue with storybook files, when it was there but now when it moved out from there we can return it

2021-01-03 06:03 UTC, simchaNielsen commented on plugins/plugin-chart-composed/package.json
> -    "@superset-ui/core": "^0.16.11",
👍 it is, return it

2021-01-03 06:05 UTC, simchaNielsen commented on plugins/plugin-chart-waterfall/test/__mocks__/waterfallProps.ts
> +    "numbersFormat": "SMART_NUMBER",
it `mocks` :) a lot of times I just copy input data from browser and past here if some inputs is updating, so it can add some difficulty then change it to consts

2021-01-03 06:08 UTC, simchaNielsen commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +import {CHART_SUB_TYPES, CHART_TYPES, Layout} from '../../plugins/plugin-chart-composed/src/components/utils';
I thought about it also at he first, but in the end I have 2 reasons why keep it out of it:
1. superset-ui also keep it out of them
2. actually we don't need them inside of package, because they not related to npm dependencies, and we can't run it without pull entire repository, so I don't see reason why keep them inside packages

2021-01-03 06:15 UTC, simchaNielsen commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +      {`SubType "${args.chartSubType}" is not applied for Bars Chart, please change "chartSubType" property to:`}
no, it's just ask for user choose other knob for chartSubType property, it's not critical, just he choose inappropriate know, so we inform him, what to choose :)

2021-01-03 06:20 UTC, simchaNielsen commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +    data={transformProps({...barsHorizontalLegendTop, queriesData: args.queriesData} as unknown as ChartProps).data}
so `ChartProps` have a lot of fields that superset inject in our types - and this is `ChartProps` but in most case we not use all these fields, for example when for composed chart all mocks took more then 1000 lines of code whe I took it from. browser, so I removed all unnecessary data to reduce mocks, but now mock not looks like `ChartProps ` because of this I do conversation

2021-01-03 06:22 UTC, simchaNielsen commented on package.json
> +    "lint": "eslint plugins/**/*.{ts,tsx}",
we don't have actual code there (now I also removed index.ts empty)
so it fails on lint:

2021-01-03 06:37 UTC, simchaNielsen commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +import {ChartProps, supersetTheme, ThemeProvider} from "@superset-ui/core";
yes, it's working according our lint rules:
![image](https://user-images.githubusercontent.com/56388545/103473219-e198ef80-4d9e-11eb-8910-5a1b74d9a6d9.png)

2021-01-03 06:45 UTC, MatanBobi commented on plugins/plugin-chart-waterfall/test/__mocks__/waterfallProps.ts
> +    "numbersFormat": "SMART_NUMBER",
I didn't see it's in mock files, sorry :)

2021-01-03 06:45 UTC, MatanBobi commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +import {ChartProps, supersetTheme, ThemeProvider} from "@superset-ui/core";
It doesn't look like it.. can you run it on this specific file? prettier adds spaces between the braces and here we don't have it.

2021-01-03 06:46 UTC, MatanBobi commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +      {`SubType "${args.chartSubType}" is not applied for Bars Chart, please change "chartSubType" property to:`}
Cool.

2021-01-03 06:49 UTC, MatanBobi commented on package.json
> +    "lint": "eslint plugins/**/*.{ts,tsx}",
Don't forget to add it once you create a shared package.

2021-01-03 06:57 UTC, MatanBobi commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +    data={transformProps({...barsHorizontalLegendTop, queriesData: args.queriesData} as unknown as ChartProps).data}
The props you're missing aren't nullable?

2021-01-03 06:57 UTC, MatanBobi commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +import {CHART_SUB_TYPES, CHART_TYPES, Layout} from '../../plugins/plugin-chart-composed/src/components/utils';
I think keeping it there for relevance and order can be good and we can remove them from build but if you think it's not a good idea then leave it :)

2021-01-03 12:38 UTC, simchaNielsen commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +    data={transformProps({...barsHorizontalLegendTop, queriesData: args.queriesData} as unknown as ChartProps).data}
no, I removed them from json

2021-01-03 12:41 UTC, simchaNielsen commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +import {ChartProps, supersetTheme, ThemeProvider} from "@superset-ui/core";
![image](https://user-images.githubusercontent.com/56388545/103478787-bd0a3b00-4dd1-11eb-8126-d7579d8d5ea8.png)

2021-01-03 12:42 UTC, simchaNielsen commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +import {ChartProps, supersetTheme, ThemeProvider} from "@superset-ui/core";
may be we need update some config?

2021-01-03 12:51 UTC, MatanBobi commented on stories/plugin-chart-composed/ComposedChart.stories.tsx
> +import {ChartProps, supersetTheme, ThemeProvider} from "@superset-ui/core";
Yeah, it looks like we're not using the prettier eslint plugin:
https://github.com/nielsen-oss/superset-viz-plugins/blob/master/.eslintrc.js

2021-01-04 06:05 UTC, closed without merging