Fix composed 2
nielsen-oss/superset-viz-plugins pull request #43
Opened 2021-04-11 07:55 UTC by simcha90

2021-04-11 08:13 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/ComposedChart.tsx
> +  currentData = useMemo(
This looks odd to me that you're editing a variable you just assigned to, wouldn't it be logically better if it will be a different variable?

2021-04-11 08:14 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/ComposedChart.tsx
> +  let currentData = useMemo(
I'd pull this function out and call it something like `removePropertiesFromData`

2021-04-11 08:15 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/ComposedChartTooltip.tsx
> +          // @ts-ignore
What is the `ts-ignore` supposed to hide here?

2021-04-11 08:17 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/utils.tsx
> +    ? // @ts-ignore
Again, why `ts-ignore`?

2021-04-11 08:17 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/utils.tsx
> +      `${formatter(Object.values(currentData[index])[breakdowns.findIndex(item => item === breakdown)]?.value)}`
This logic is too complicated for me to understand.. I'd pull it out to functions and give it a proper naming.

2021-04-11 08:17 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/utils.tsx
> +    // @ts-ignore
Why the `ts-ignore`?

2021-04-11 08:20 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/plugin/utils.ts
> +  useOrderByMetric0: boolean;
It's called `use` which implies a `React Hook` but it's a boolean?

2021-04-11 08:32 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/ComposedChartTooltip.tsx
> +  numbersFormat: string;
Maybe we should create a different type and not define it on the fly?

2021-04-11 08:51 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/ComposedChartTooltip.tsx
> +          const item = isBarChartOrder ? initItem?.payload[index] : initItem;
If `initItem` is undefined, you'll get `false` as the `item`, is that the wanted behavior?
(since `initItem?.payload[index]` will return false)

2021-04-11 08:52 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/utils.tsx
> +export type BarChartValue = { id: string; value: number; name: string; color: string };
Maybe create a type for this one and not create it on the fly?

2021-04-11 08:53 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/utils.tsx
>  type ChartElementProps = {
I think all the types should be located together and having a function before the type definition breaks the order..

2021-04-11 08:54 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/utils.tsx
>  type ChartElementProps = {
So as a general rule I'd go with something like this:
```
imports

types

styled components

functions

component's render
```

2021-04-11 08:55 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/utils.tsx
> +  isBarChartOrder,
I'm not sure the prop name really infers to what it does. What's the actual purpose of it?

2021-04-11 08:57 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/utils.tsx
> +  let dataKey: string | Function = breakdown;
Having it both as a string or a function looks odd to me, maybe it will be better to create a different variable to store the function?

2021-04-11 08:59 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/utils.tsx
> +        currentData.map((entry: { [key: string]: BarChartValue }) => {
I'd put the type declaration somewhere else. Also, entry doesn't sound to me like a meaningful name and what's the index's purpose here?

2021-04-11 08:59 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/utils.tsx
> +          const otherProps = entry[index] ? {} : { fillOpacity: 0 };
Since you have two lines that need `entry[index]` to have a value, I'd put it in an `if` statement .

2021-04-11 09:04 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/plugin/configs/orderBy.ts
> +      label: t(`Use sorting for ${title} ${index === undefined ? '' : index + 1}`),
It's either a string or a number? it's odd to me.

2021-04-11 09:05 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/plugin/configs/orderBy.ts
> +            ? ' (if you use "BarChart", can be applied correctly only without composition with other charts)'
"BarChart can not be applies correctly when composing it with other charts"?

2021-04-11 09:06 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/plugin/configs/orderBy.ts
> +        index === undefined || !!form_data?.[source]?.[index ?? 0],
Why do you need the `[index ?? 0]`? If you'll get there it means that index is not `undefined`. Can it be `null`?

2021-04-11 09:08 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/utils.tsx
> +  if (isBarChartOrder) {
I'd break this function to multiple functions, it's too complicated for me at the moment.

2021-04-11 09:09 UTC, MatanBobi requested changes
I left some comments. Please remove all `ts-ignore`s and lets find a way to handle them without the ignores.

2021-04-11 09:43 UTC, simcha90 commented on plugins/plugin-chart-composed/src/components/ComposedChart.tsx
> +  currentData = useMemo(
![image](https://user-images.githubusercontent.com/56388545/114299389-7a888680-9ac3-11eb-91ff-758a149d1cf1.png)
I do it a lot of times, so not sure crate new variable every time is better way

2021-04-11 09:49 UTC, simcha90 commented on plugins/plugin-chart-composed/src/components/ComposedChart.tsx
> +  let currentData = useMemo(
I created hook for all this stuff

2021-04-11 09:51 UTC, simcha90 commented on plugins/plugin-chart-composed/src/components/ComposedChartTooltip.tsx
> +          // @ts-ignore
this feature is tweak for re-charts that used in 10% of cases or less, but it has different data structure, if I will add this to typing it will require change a lot of places in code and also will add some messing to typing, in almost all cases this tructure is not rellevant

2021-04-11 09:51 UTC, simcha90 commented on plugins/plugin-chart-composed/src/components/utils.tsx
> +    ? // @ts-ignore
same

2021-04-11 10:06 UTC, simcha90 commented on plugins/plugin-chart-composed/src/components/ComposedChartTooltip.tsx
> +          const item = isBarChartOrder ? initItem?.payload[index] : initItem;
yes, `isBarChartOrder` responsible that this data wii be there

2021-04-11 10:11 UTC, simcha90 commented on plugins/plugin-chart-composed/src/components/utils.tsx
>  type ChartElementProps = {
I re-ranged some of types, but for some functions I prefer to leave `types` of `function arguments` near the function itself in order to not search it in entire files

2021-04-11 11:59 UTC, simcha90 commented on plugins/plugin-chart-composed/src/components/utils.tsx
> +  let dataKey: string | Function = breakdown;
it's same answer - it's a tweak for re-charts, to support this functionality we need tweak some properties

2021-04-11 12:04 UTC, simcha90 commented on plugins/plugin-chart-composed/src/plugin/configs/orderBy.ts
> +      label: t(`Use sorting for ${title} ${index === undefined ? '' : index + 1}`),
it can be also `undefined`, it's like empty value, if we pass undefined, just write anything

2021-04-11 12:05 UTC, simcha90 commented on plugins/plugin-chart-composed/src/plugin/configs/orderBy.ts
> +            ? ' (if you use "BarChart", can be applied correctly only without composition with other charts)'
it's not exactly a sense, I wanted to say that this option works for all charts also if they composed and also for bar chart if it's not composed with other charts, I think @amitmiran137 said that it's ok

2021-04-11 12:08 UTC, simcha90 commented on plugins/plugin-chart-composed/src/plugin/configs/orderBy.ts
> +        index === undefined || !!form_data?.[source]?.[index ?? 0],
it can be `undefined` it's just function property, thatI'm passing, in one case it used as index for `groupby`, and for `metrics` meantime we decided that we have meantime only one property, so meantime we saved logic just left only one value in this case we are passing `undefined` it means also write different `text` but add index `0`

2021-04-11 12:09 UTC, simcha90 commented on plugins/plugin-chart-composed/src/components/utils.tsx
> +  if (isBarChartOrder) {
it's already single function :)

2021-04-11 12:34 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/ComposedChart.tsx
> +  currentData = useMemo(
Ok 👍🏻

2021-04-11 12:34 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/ComposedChartTooltip.tsx
> +          // @ts-ignore
Can't you extend the type and define the specific property as nullable?

2021-04-11 12:35 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/ComposedChartTooltip.tsx
> +          const item = isBarChartOrder ? initItem?.payload[index] : initItem;
If `isBarChartOrder` is responsible for it you can remove the optional chaining, can't you?

2021-04-11 12:36 UTC, simcha90 commented on plugins/plugin-chart-composed/src/components/ComposedChartTooltip.tsx
> +          // @ts-ignore
it's property that use as `string` in recharts and all charts in this plugin use it as `string`, in my specific case I use same property as object and put values indie of it :)

2021-04-11 12:37 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/utils.tsx
>  type ChartElementProps = {
I think it's better to have them all located at the same place for other maintainers to make it easy for other maintainers to understand what's going on.
This comment actually was because the `type` definition was located between functions so I thought they should be located higher as I wrote in the example.

2021-04-11 12:38 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/utils.tsx
> +  if (isBarChartOrder) {
I mean that all the functionality inside can be separated to different functions for clarity.

2021-04-11 14:56 UTC, simcha90 commented
> I left some comments. Please remove all `ts-ignore`s and lets find a way to handle them without the ignores.

I removed ts-ignores that was added by this PR

2021-04-11 18:17 UTC, simcha90 commented on plugins/plugin-chart-composed/src/components/utils.tsx
>  type ChartElementProps = {
but if I have function with `n arguments` why need go to the beginning of the file to find type of this arguments if they relevant only for this function? mmm... it's add indirection in code I think... also there is unnecessary jumping in file between lines of code.... thoughts...

2021-04-12 07:37 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/components/utils.tsx
>  type ChartElementProps = {
No problem, it's just a preference, probably should be labeled as [Dust].

2021-04-12 07:38 UTC, MatanBobi commented on plugins/plugin-chart-composed/src/plugin/configs/orderBy.ts
> +        index === undefined || !!form_data?.[source]?.[index ?? 0],
The only thing I'm saying is that you're first ternary makes sure that `index` is defined so you don't need the `??`

2021-04-12 07:38 UTC, MatanBobi approved these changes

2021-04-12 07:41 UTC, simcha90 commented on plugins/plugin-chart-composed/src/plugin/configs/orderBy.ts
> +        index === undefined || !!form_data?.[source]?.[index ?? 0],
👍

2021-04-12 07:55 UTC, merged