New Bubble chart pull request
nielsen-oss/superset-viz-plugins pull request #94
Opened 2021-11-08 21:06 UTC by mdkhanNielsen

I have added a few features on the bubble chart
1. bubble chart x axis log axis
2. y axis log axis
3. legend
4. display chart color
5. no series chart
6. option to add cartesian grid
7. tooltip data
8. More options to place legends
9. 4 stories on the story book

2021-11-08 21:08 UTC, simcha90 approved these changes

2021-11-10 14:08 UTC, amitmiran137 commented on stories/plugin-chart-waterfall/WaterfallChart.stories.tsx
> +import { supersetTheme, ThemeProvider } from '@superset-ui/core';
is this mandatory?

2021-11-10 14:15 UTC, amitmiran137 requested changes
a few inital comments 
also delete package-lock.,json

2021-11-10 14:15 UTC, amitmiran137 commented on plugins/plugin-chart-bubble/src/BubbleChart.tsx
> +  legends = legends.slice(0, 18);
why are we slicing here?

2021-11-10 14:41 UTC, mdkhanNielsen commented on stories/plugin-chart-waterfall/WaterfallChart.stories.tsx
> +import { supersetTheme, ThemeProvider } from '@superset-ui/core';
this was in the waterfall chart (I didn't work on that). However, while linting i was getting a lint error for unused variable `ChartProps`, I just removed that one. Didn't explore whether supersetTheme or ThemeProvider is mandatory or not

2021-11-11 20:05 UTC, mdkhanNielsen commented on plugins/plugin-chart-bubble/src/BubbleChart.tsx
> +  legends = legends.slice(0, 18);
I added a new controls 'Max Number of Legends' so, its not hard coded any more. However, the default is 18

2021-11-11 20:06 UTC, mdkhanNielsen commented
> a few inital comments also delete package-lock.,json

I deleted the package-lock and yarn-lock file

2021-11-17 16:24 UTC, jayakrishnankk commented
@mdkhanNielsen , @amitmiran137 - is this ready to be merged ?

2021-12-02 17:35 UTC, jayakrishnankk commented
@amitmiran137 - what was the issue that we discussed in our superset meeting about bubble chart ? @mdkhanNielsen is not aware of any color issue.

2021-12-05 15:36 UTC, merged